# Generated by Django 3.2.5 on 2022-11-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Forms',
        ),
        migrations.DeleteModel(
            name='FQ',
        ),
        migrations.DeleteModel(
            name='LCs',
        ),
        migrations.DeleteModel(
            name='MC',
        ),
        migrations.DeleteModel(
            name='MCTEAM',
        ),
        migrations.DeleteModel(
            name='social_media_link',
        ),
    ]
