# Generated by Django 3.2.5 on 2022-11-21 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_mcteam_mcparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date'),
        ),
    ]
