# Generated by Django 3.2.5 on 2022-11-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
