# Generated by Django 3.2.5 on 2022-11-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_forms_fq_lcs_mc_mcteam_social_media_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcteam',
            name='social_links',
        ),
    ]
