# Generated by Django 3.2.5 on 2022-11-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='AIESECERS_or_youth',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='limited_places_OR_nonlimited',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='link_page',
            field=models.TextField(blank=True, null=True),
        ),
    ]
