# Generated by Django 3.2.5 on 2022-11-10 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_mcteam_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_media_link',
            name='departents',
            field=models.TextField(default=datetime.date(2022, 11, 10)),
            preserve_default=False,
        ),
    ]
