# Generated by Django 3.2.5 on 2022-11-15 14:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_social_media_link_departents'),
    ]

    operations = [
        migrations.AddField(
            model_name='mc',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='mcteam',
            name='mcParent',
            field=models.ForeignKey(default=datetime.date.today, on_delete=django.db.models.deletion.CASCADE, to='app.mc'),
            preserve_default=False,
        ),
    ]
