# Generated by Django 3.2.5 on 2022-11-15 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20221115_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcteam',
            name='deparment',
            field=models.TextField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
