# Generated by Django 3.2.5 on 2022-12-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221226_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
